# Generated by Django 4.0.1 on 2024-07-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
