# Generated by Django 4.0.1 on 2024-07-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qr_code',
        ),
    ]
