# Generated by Django 4.0.1 on 2024-08-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_chatmessage_options_profile_qr_code'),
        ('api', '0017_profile_qr_code'),
    ]

    operations = [
    ]
